name: Code Quality Check

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar Linter
        run: npm run lint

      # --- NOTIFICACIÓN SI TODO SALE BIEN ---
      - name: Enviar correo de éxito
        if: success() && github.event_name == 'pull_request'
        uses: dawidd6/action-send-mail@v3
        with:
          # Debo cambiar el servidor SMTP cuando use otro proveedor de correo (gmail, outlook, etc.)
          server_address: smtp.hostinger.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "✅ PR Lista: ${{ github.event.pull_request.title }}"
          to: didacusdev@gmail.com
          # Importante: Hostinger exige que el 'from' coincida con la cuenta, gmail
          from: "GitHub Robot <${{ secrets.MAIL_USERNAME }}>" 
          body: |
            ¡Enhorabuena! 🎉
            
            La PR "${{ github.event.pull_request.title }} - ${{ github.event.pull_request.number }}" ha pasado el linter sin errores.
            
            Es necesaria tu intervención para realizar el merge, ingresa al siguiente enlace para revisar y aprobar la PR:
            ${{ github.event.pull_request.html_url }}

      # --- NOTIFICACIÓN SI ALGO FALLA ---
      - name: Enviar correo de error
        if: failure() && github.event_name == 'pull_request'
        uses: dawidd6/action-send-mail@v3
        with:
          # Debo cambiar el servidor SMTP cuando use otro proveedor de correo (gmail, outlook, etc.)
          server_address: smtp.hostinger.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "❌ Error de Calidad: ${{ github.event.pull_request.title }}"
          to: didacusdev@gmail.com
          # Importante: Hostinger exige que el 'from' coincida con la cuenta, gmail
          from: "GitHub Robot <${{ secrets.MAIL_USERNAME }}>" 
          body: |
            ¡Atención! ⚠️
            
            El linter ha encontrado errores en la PR: "${{ github.event.pull_request.title }}".
            El código no cumple con las reglas de estilo configuradas (posiblemente un console.log, comillas dobles en lugar de simples o falta de punto y coma).
            
            Revisa los detalles aquí:
            ${{ github.event.pull_request.html_url }}/checks